### PR TITLE
Three new code samples - library loans, Book a space and scholarships.

### PR DESCRIPTION
**Pull request by jesegher**
> By submitting this pull request, you agree to the [contribution guidelines](CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | yes                               
| New sample?     | yes                               |
| Related issues? | fixes #X, partially #Y, mentioned in #Z |

## What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
Two new code samples were added. Library loans and Scholarships.

### CODE REVIEW

**Comment by jesegher** [comment]
Three new code samples. Library Loans and scholarships were submitted already. Added book a space on 5/18.

**Comment by jesegher** [comment]
@dcashpeterson I know you merged the first request. I was wondering if you could do the same for this one?

**Comment by jesegher** [comment]
Update sample.json in bookspaces.

**Comment by dcashpeterson** [comment]
> @dcashpeterson I know you merged the first request. I was wondering if you could do the same for this one?

@jesegher I will do my best to get to this soon.

**Comment by jesegher** [comment]
> > @dcashpeterson I know you merged the first request. I was wondering if you could do the same for this one?
> 
> @jesegher I will do my best to get to this soon.

@dcashpeterson I chatted with Vesa and he will merge it tomorrow. thank you though.

**Pull request merged**
