### PR TITLE
Tfl status sample update

### PR DESCRIPTION
**Pull request by anoopt**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes                               |
| New feature?    | yes                               |
| New sample?     | no                               |
| Related issues? | NA |

## What's in this Pull Request?

Updated the sample to SPFx 1.13.0 and fixed some issues related to the Viva connections mobile app.

### CODE REVIEW

**Comment by dcashpeterson** [comment]
Thanks for the update. We'll review and publish shortly.

**Comment by anoopt** [comment]
Thank you Derek. For some reason the svg icons are not loading in the quick view in mobile app. So, I'll take a look at that and add more commits and let you know once done.

I thought I had fixed it by using require. But I see that it worked only when I was developing. After publishing it has stopped working.

**Comment by dcashpeterson** [comment]
@anoopt If you can get an update to me tomorrow I can review and approve it on Monday. If not, no rush. David and I are reviewing the PRs then.

**Comment by dcashpeterson** [comment]
@anoopt Thank you for the update. I have merged this into the main branch.

**Pull request merged**
