### PR TITLE
Merging Security Monitor ACE

### PR DESCRIPTION
**Pull request by dcashpeterson**
Merging Security Monitor ACE to main

### CODE REVIEW

**Comment by dcashpeterson** [comment]
@ArijitCloud Thanks so much for the sample. I have merged it into the Main branch.

**Comment by ArijitCloud** [comment]
L1MTG6fqtd
@dcashpeterson Please let me know if this works, or I can upload another one.

**Comment by dcashpeterson** [comment]
Those are prefect. Thanks I have it scheduled to go out on Thursday.

**Comment by ArijitCloud** [comment]
@dcashpeterson My twitter I don't have professional contents. But here it is, https://twitter.com/cloudarijit
It should be ok either way :)

**Pull request merged**
