### PR TITLE
Contributing new SPFx ACEs sample for the first time

### PR DESCRIPTION
**Pull request by MaheeTech**
> This pull request includes new ACEs card which is ApplyLeave card with a feature set out of office and also this card shows leave history where user can configure to view a My Holiday Card in Dashboard page.

This PR includes two ACEs, first card (ApplyLeave & Set out of office Card) talks about how to submit a leave and in parallel user can set out of office message for that duration. Second card (My Holidays) talks about list of holidays for the selected country.

### CODE REVIEW

**Comment by dcashpeterson** [comment]
@MaheeTech Thank you for your submission. I was reviewing this release and it doesn't look like the appropriate graph permissions are included in the package-solution.json file. If you could please add those then I can retest. If you need assistance please see this reference. https://learn.microsoft.com/en-us/sharepoint/dev/spfx/use-aad-tutorial#configure-the-api-permissions-requests

**Comment by MaheeTech** [comment]
@dcashpeterson thank you.. I add API permission  in package-solution.json file....

**Comment by MaheeTech** [comment]
@dcashpeterson  I added required changes in README file... thank you for your time in reviewing the code....

**Comment by dcashpeterson** [comment]
Closed due to inactivity. If you would still like to submit this sample we would love to have it. Please fix the issues we discussed and resubmit it.

**Pull request closed without merging**
