### PR TITLE
Added sample - My M365 Groups

### PR DESCRIPTION
**Pull request by nanddeepn**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     |  yes                               |

## What's in this Pull Request?

Adaptive Card Extension that shows logged-in user M365 Unified Groups.

### CODE REVIEW

**Comment by PopWarner** [comment]
Thanks for the sample @nanddeepn! 💜🧡 We will get this processed soon. I'll reach out directly and chat with you to see if you are interested in providing a demo on it?

**Comment by nanddeepn** [comment]
Thank you @PopWarner 
Definitely, interested to demo it to PnP community!

**Comment by dcashpeterson** [comment]
@nanddeepn  Thank you so much for the sample. I approved the PR and it is now live in the gallery. @PopWarner will reach out if he hasn't already to talk about the possibility of doing a demo.

**Comment by nanddeepn** [comment]
Thank you @dcashpeterson and @PopWarner for your review and accepting the sample.
Luise Freese has confirmed a slot to demo this solution during PnP call on 7 April, 2022. Thank you!

**Pull request merged**
