### PR TITLE
New sample: Ace today's lunch

### PR DESCRIPTION
**Pull request by luismanez**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                                |
| New feature?    | no                               |
| New sample?     | yes                               |
| Related issues? |  |

## What's in this Pull Request?

This adaptive card extension sample renders information about Today´s lunch. Data is managed in a SharePoint list with a list item per day of the week.

### CODE REVIEW

**Comment by dcashpeterson** [comment]
Thanks for the pull request. We review it and get it posted shortly.

**Comment by PopWarner** [comment]
Great sample @luismanez! 🙏🏻👍🏻🧡💜

Would you be willing to demo this sample on future PnP call? 🙂

**Comment by luismanez** [comment]
Thanks @PopWarner ... How can I say no to my favorite community?! count me in! :)

**Comment by PopWarner** [comment]
> Thanks @PopWarner ... How can I say no to my favorite community?! count me in! :)

LOVE IT! I'll reach out to you directly to schedule! 👏👏☺

**Pull request merged**
