### PR TITLE
Added new sample MyEmails

### PR DESCRIPTION
**Pull request by siddharth-vaghasia**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| New sample?     | yes                               |

## What's in this Pull Request?

Added new sample ACE for showing current user's emails in ACEs

### CODE REVIEW

**Comment by dcashpeterson** [comment]
@siddharth-vaghasia thank you for your sample. I am in the process of reviewing it and will get it approved as soon as I can. Question, the ReadMe indicates that this is targeted to 1.13 but the package.json uses 1.14 beta. Do you want to pick one and update? Thanks again!

**Comment by siddharth-vaghasia** [comment]
@dcashpeterson  - sure, will update.

**Comment by siddharth-vaghasia** [comment]
if you can please advise on what the should be a badge for the 1.14 beta? Tried some combinations but it not worked...

or it would be https://img.shields.io/badge/version-1.14.0-green.svg ?

**Comment by dcashpeterson** [comment]
@siddharth-vaghasia go ahead and use the 1.14.0-green. I can check with folks and make sure it's correct and if it's the only change I can update it later if it's incorrect.

**Comment by siddharth-vaghasia** [comment]
@dcashpeterson  - I have updated to spfx 1.14....

**Comment by dcashpeterson** [comment]
@siddharth-vaghasia Thank you for the sample. I apologize it took me so long. @PopWarner will reach out to set up a demo if he hasn't already.

**Pull request merged**
