### PR TITLE
Primary text card people details

### PR DESCRIPTION
**Pull request by XLR8-0**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                              |
| New feature?    | no                               |
| New sample?     | yes                               |

## What's in this Pull Request?

> This Adaptive Card Extension shows general CRUD operations for people details using SharePoint list and Adaptive Card which involves multiple QuickViews and pnp js.

### CODE REVIEW

**Comment by XLR8-0** [comment]
Hi @dcashpeterson, thank you for the reply. I just checked the code and found that the stated warning is coming. Could you please update line 8 with `Connect-PnPOnline -Url $siteUrl -Interactive`  or do you want me to update the same and push the code again?

**Comment by dcashpeterson** [comment]
@XLR8-0 Thanks for the update. I will get this reviewed as soon as I can.

**Comment by dcashpeterson** [comment]
@XLR8-0 Hi there. I am looking at this again and will approve it but the check check mark image is missing after the update. It is looking for something in the SiteAssets library. You might want to consider bundling that into the package in an update.

**Comment by XLR8-0** [comment]
Thanks @dcashpeterson . I have updated that part and will update it sortly.

**Pull request merged**
