### PR TITLE
follow documents ace

### PR DESCRIPTION
**Pull request by aaclage**
> By submitting this pull request, you agree to the [contribution guidelines](CONTRIBUTING.md)

> If you aren't familiar with how to contribute to open-source repositories using GitHub, or if you find the instructions on this page confusing, [sign up](https://forms.office.com/Pages/ResponsePage.aspx?id=KtIy2vgLW0SOgZbwvQuRaXDXyCl9DkBHq4A2OG7uLpdUREZVRDVYUUJLT1VNRDM4SjhGMlpUNzBORy4u) for one of our [Sharing is Caring](https://pnp.github.io/sharing-is-caring/#pnp-sic-events) events. It's completely free, and we'll guide you through the process.

|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | no                               |
| New feature?    | yes                               |
| New sample?     | yes                             |
| Related issues? |  |

## What's in this Pull Request?
This example shows how to build an ACE with multiple card and quick views to get current user **"Follow Documents"** marked by Office 365 home page > Favorites Tab.

The sample uses **Microsoft Graph queries** with "List followed items" and generate Thumbnails with links to support access to files.

### Features

**ACE Properties:**
- Include custom Link to redirect from ACE WebPart
- Select View "Slider or List" with associated adaptive Card
- Mockup Data (dummy data for test if no follow document is selected)

**ACE WebPart "Follow" button:**
- **Slider View:**
  - Search for file
  - Display files as gallery
  - Site name where file is located and link to site
  - File name and link to File to open in the web
  - Slider to rotate Files with associated counting
- 5 additional support options 
  - Teams icon - Share to Teams link with file url reference
  - Folder icon - Link to folder where file is located
  - Unfollow icon - unfollow file from list
  - Info icon - Link to file properties page
  - Download icon - Link to download file
  - Preview icon - Expand/collapse of thumbnail of file (generated by Microsoft Graph)
  - Refresh icon - Refresh data

 - **List View:**
  List files 
Search for file
Display icon of File
File Title and link to open in the web
Folder icon - Link to folder where file is located
Unfollow icon - unfollow file from list
Refresh icon - Refresh data

### CODE REVIEW

**Comment by dcashpeterson** [comment]
hi @aaclage  Thanks for submitting a sample. We will review it as soon as we can.

-Derek

**Comment by aaclage** [comment]
@dcashpeterson made some optimization on the query, sorry for the inconvenience.

**Comment by PopWarner** [comment]
@aaclage, no problem on the additional commits. 😃

**Comment by aaclage** [comment]
@PopWarner @dcashpeterson to finalize, included a missing feature, update associated documentation. I will stop with updates.

**Comment by dcashpeterson** [comment]
@aaclage  no worries at all. I will review next week. Thanks again for the submission. :)

**Comment by aaclage** [comment]
Hi @dcashpeterson @PopWarner, 

For any update/change feel free to contact me.

**Comment by aaclage** [comment]
Hi @dcashpeterson update the code to exclude files with 'size' 0, this was the reason was retriving error.

**Comment by dcashpeterson** [comment]
@aaclage Thanks for the update. Sorry it took me so long to get to it.

**Comment by aaclage** [comment]
@dcashpeterson 
It was also my fault, also did a lot of changes and thank you for your support.

**Pull request merged**
