### PR TITLE
Merge MyShifts Sample

### PR DESCRIPTION
**Pull request by dcashpeterson**
Merging Shifts sample.

### CODE REVIEW

**Comment by dcashpeterson** [comment]
@siddharth-vaghasia Thanks for the sample. I merged it into main today. reach out to @PopWarner or I if you would like to get on the schedule to do a demo on one of the community calls.

**Comment by siddharth-vaghasia** [comment]
@dcashpeterson thanks for approving PR, @PopWarner  - I would be happy to demo this in community calls based on next slot available :)

**Comment by siddharth-vaghasia** [comment]
@PopWarner @dcashpeterson - just checking again if we have an available slot for demoing this ACE component in community call ?

**Comment by dcashpeterson** [comment]
@siddharth-vaghasia I reached out on Twitter to get this scheduled.

**Pull request merged**
